### ISSUE TITLE
Future plans

### ISSUE THREAD

**Issue by mimshwright** [as3/as3-utils#17]
Hey everyone, 

I just wanted to ask everyone what their thoughts are on the future of the library. I know AS3 isn't very popular these days so interest may be waning in the project. I suppose my plans for it would be to just keep it around and add to it if there are any new pieces to add. A more ambitious plan might be to try to port some of this to JS or Dart or another language. Anyway, please chime in if you have any thoughts on the subject.

Thanks,
Mims Wright

**Comment by johnlindquist** [comment]
I'm still actively using as3-utils on projects, but I can't remember the
last time I had to add a new util.

As for JS, it seems like there are a few "standards" around certain areas
(jquery = dom manipulation, underscore = collections, etc), but it may be
useful to see if things like the date/color/number/etc packages have JS lib
equivalents.

Since everyone just combines/minifies JS libs together it doesn't make too
much sense to have an all-encompassing "js-utils" project. There's a few
"boilerplate"-type projects out there that kind of accomplish that already.

On Mon, Apr 2, 2012 at 1:44 PM, Mims H. Wright <
reply@reply.github.com
